name: Claude PR Review

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  claude-review:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      pull-requests: write
      
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Create GitHub App Token  
        uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ secrets.CLAUDE_GITHUB_APP_ID }}
          private-key: ${{ secrets.CLAUDE_GITHUB_PRIVATE_KEY }}
          
      - name: Claude PR Review
        uses: anthropics/claude-pr-review@v1
        with:
          github_token: ${{ steps.app-token.outputs.token }}
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          focus_areas: |
            - GRPO algorithm implementation correctness
            - RookWorld integration compatibility  
            - Chess move validation logic
            - Stockfish integration parameters
            - Reward function accuracy
            - Code structure and documentation
          review_level: "detailed"
          auto_approve: false