name: Claude

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  issues:
    types: [opened, assigned]

jobs:
  claude:
    if: contains(github.event.comment.body, '@claude') || github.event_name == 'issues'
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      issues: write
      pull-requests: write
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Create GitHub App Token
        uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ secrets.CLAUDE_GITHUB_APP_ID }}
          private-key: ${{ secrets.CLAUDE_GITHUB_PRIVATE_KEY }}
          
      - name: Claude PR Action
        uses: anthropics/claude-github-action@v1
        with:
          trigger_phrase: "@claude"
          github_token: ${{ steps.app-token.outputs.token }}
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}